# Generated by Django 5.1.1 on 2024-12-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_data_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='note',
            field=models.CharField(default='No Note yet!', max_length=250),
        ),
    ]
