# Generated by Django 5.1.1 on 2024-10-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cash_out_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_in',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cash_out',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
